export enum EmailType {
  WELCOME = 'WELCOME',
  NEW_MATCH = 'NEW_MATCH',
  NEW_MESSAGE = 'NEW_MESSAGE',
  CREDIT_UPDATE = 'CREDIT_UPDATE',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  BUNDLE_EXPIRY_WARNING = 'BUNDLE_EXPIRY_WARNING',
}
