import { HttpStatus } from '@nestjs/common';

export const DOMAIN_EXCEPTION_HTTP_MAP: Record<string, HttpStatus> = {
  ProfileNotFoundException: HttpStatus.NOT_FOUND,
  ProfileAlreadyExistsException: HttpStatus.CONFLICT,
  InsufficientCreditsException: HttpStatus.PAYMENT_REQUIRED,
  MissingTargetIdentityException: HttpStatus.BAD_REQUEST,
  IdentityNotFoundException: HttpStatus.NOT_FOUND,
  SelfLikeException: HttpStatus.BAD_REQUEST,
  AlreadyLikedException: HttpStatus.CONFLICT,
  LikeNotFoundException: HttpStatus.NOT_FOUND,
  InvalidLikeStateException: HttpStatus.BAD_REQUEST,
  MessageNotFoundException: HttpStatus.NOT_FOUND,
  MatchNotFoundException: HttpStatus.NOT_FOUND,
  SelfBlockException: HttpStatus.BAD_REQUEST,
  BlockTargetNotFoundException: HttpStatus.NOT_FOUND,
  AlreadyBlockedException: HttpStatus.CONFLICT,
  BlockNotFoundException: HttpStatus.NOT_FOUND,
  AccountAlreadyExistsException: HttpStatus.CONFLICT,
  RegistrationPendingException: HttpStatus.CONFLICT,
  AccountNotFoundException: HttpStatus.NOT_FOUND,
  UnverifiedAccountException: HttpStatus.UNAUTHORIZED,
  SocialAccountAlreadyLinkedException: HttpStatus.CONFLICT,
  DeletedAccountReverificationException: HttpStatus.CONFLICT,
  AuthTypeMismatchException: HttpStatus.CONFLICT,
  UserNotFoundException: HttpStatus.NOT_FOUND,
  UnsupportedAuthMethodException: HttpStatus.CONFLICT,
  AdminUserNotFoundException: HttpStatus.NOT_FOUND,
  IdentityAlreadyExistsException: HttpStatus.CONFLICT,
  IdentityAlreadyClaimedException: HttpStatus.CONFLICT,
  UnsupportedSecondaryIdentityException: HttpStatus.CONFLICT,
  IdentityAlreadyInUseException: HttpStatus.CONFLICT,
  UnsupportedUnlinkMethodException: HttpStatus.CONFLICT,
  PrimaryCredentialUnlinkException: HttpStatus.CONFLICT,
  CredentialAlreadyLinkedException: HttpStatus.CONFLICT,
  PrimaryIdentityConstraintViolationException: HttpStatus.CONFLICT,
  LedgerEntryNotFoundException: HttpStatus.NOT_FOUND,
  InvalidCreditSourceException: HttpStatus.BAD_REQUEST,
  DeviceNotFoundException: HttpStatus.NOT_FOUND,
  DeviceTokenAlreadyExistsException: HttpStatus.CONFLICT,
  InstagramGraphApiException: HttpStatus.BAD_GATEWAY,
  MissingInstagramConfigException: HttpStatus.INTERNAL_SERVER_ERROR,
  OtpRateLimitExceededException: HttpStatus.TOO_MANY_REQUESTS,
  InvalidOtpException: HttpStatus.BAD_REQUEST,
};
