/**
 * Exhaustive string-literal union of every structured log event name.
 *
 * Naming convention: `RESOURCE_ACTION` in UPPER_SNAKE_CASE.
 *
 * Usage:
 * ```ts
 * this.logger.event(LOG_EVENT.LIKE_CREATED, { likeId, userId });
 * ```
 *
 * **Do NOT add free-text strings at call-sites.** All event names must be
 * declared here first. This keeps BigQuery queries predictable and catches
 * typos at compile time.
 */
export type LogEvent =
  // ── Request Lifecycle ──────────────────────────────────────────────────────
  | 'REQUEST_RECEIVED'
  | 'REQUEST_COMPLETED'
  | 'REQUEST_FAILED'

  // ── Authentication ─────────────────────────────────────────────────────────
  | 'USER_AUTHENTICATED'
  | 'USER_AUTHENTICATION_FAILED'
  | 'USER_REGISTERED'
  | 'USER_PROVISIONED'
  | 'SECONDARY_AUTH_ADDED'
  | 'USER_SIGNED_OUT'

  // ── Likes ──────────────────────────────────────────────────────────────────
  | 'LIKE_CREATED'
  | 'LIKE_DELETED'
  | 'LIKE_LABEL_UPDATED'
  | 'LIKE_CREATION_DENIED'

  // ── Blocks ─────────────────────────────────────────────────────────────────
  | 'BLOCK_CREATED'
  | 'BLOCK_REMOVED'

  // ── Chats ──────────────────────────────────────────────────────────────────
  | 'CHAT_HISTORY_CLEARED'

  // ── Credits ────────────────────────────────────────────────────────────────
  | 'CREDITS_BALANCE_CHECKED'
  | 'CREDITS_GRANTED'
  | 'CREDITS_DEDUCTED'
  | 'CREDITS_EXPIRY_BATCH_STARTED'
  | 'CREDITS_EXPIRY_BATCH_COMPLETED'
  | 'CREDITS_EXPIRY_WARNING_SENT'

  // ── Matches ────────────────────────────────────────────────────────────────
  | 'MATCH_CREATED'
  | 'MATCH_DISSOLVED'
  | 'MATCH_RESOLUTION_TRIGGERED'
  | 'MATCH_RESOLUTION_FAILED'

  // ── Subscriptions & Payments ───────────────────────────────────────────────
  | 'TRANSACTION_RECORDED'
  | 'META_WEBHOOK_VERIFIED'
  | 'SUBSCRIPTION_PURCHASE_INITIATED'
  | 'SUBSCRIPTION_PURCHASE_COMPLETED'
  | 'SUBSCRIPTION_PURCHASE_FAILED'
  | 'SUBSCRIPTION_ACTIVATED'
  | 'SUBSCRIPTION_CANCELLED'
  | 'SUBSCRIPTION_RENEWED'
  | 'SUBSCRIPTION_EXPIRED'
  | 'SUBSCRIPTION_REFUNDED'
  | 'SUBSCRIPTION_WEBHOOK_RECEIVED'
  | 'SUBSCRIPTION_WEBHOOK_PROCESSED'
  | 'SUBSCRIPTION_WEBHOOK_FAILED'

  // ── Notifications ──────────────────────────────────────────────────────────
  | 'NOTIFICATION_REQUESTED'
  | 'NOTIFICATION_QUEUED'
  | 'NOTIFICATION_SENT'
  | 'NOTIFICATION_FAILED'
  | 'PUSH_NOTIFICATION_SENT'
  | 'PUSH_NOTIFICATION_FAILED'
  | 'EMAIL_QUEUED'
  | 'EMAIL_SENT'
  | 'EMAIL_FAILED'

  // ── Profiles & Identities ──────────────────────────────────────────────────
  | 'PROFILE_CREATED'
  | 'PROFILE_UPDATED'
  | 'PROFILE_DELETED'
  | 'PREFERENCES_UPDATED'
  | 'ACCOUNT_DELETED'
  | 'IDENTITY_CLAIMED'
  | 'IDENTITY_CREATED'
  | 'IDENTITY_RESOLVED'
  | 'IDENTITY_UPDATED'
  | 'IDENTITY_DELETED'
  | 'IDENTITY_VERIFIED'

  // ── Workflows ──────────────────────────────────────────────────────────────
  | 'INSTAGRAM_IDENTITY_LINKED'
  | 'SOCIAL_IDENTITY_VERIFIED'

  // ── Subscriptions ──────────────────────────────────────────────────────────
  | 'SUBSCRIPTION_EXPIRED_BATCH'
  | 'MATCH_RESOLUTION_COMPLETED'

  // ── Pub/Sub ────────────────────────────────────────────────────────────────
  | 'PUBSUB_MESSAGE_RECEIVED'
  | 'PUBSUB_MESSAGE_ROUTED'
  | 'PUBSUB_MESSAGE_PROCESSED'
  | 'PUBSUB_MESSAGE_FAILED'
  | 'PUBSUB_EVENT_PUBLISHED'
  | 'PUBSUB_PUBLISH_FAILED'

  // ── Audit ──────────────────────────────────────────────────────────────────
  | 'AUDIT_EVENT_EMITTED'
  | 'AUDIT_EVENT_FAILED'

  // ── External Services ──────────────────────────────────────────────────────
  | 'EXTERNAL_REQUEST_STARTED'
  | 'EXTERNAL_REQUEST_COMPLETED'
  | 'EXTERNAL_REQUEST_FAILED'

  // ── Devices ────────────────────────────────────────────────────────────────
  | 'DEVICE_REGISTERED'
  | 'DEVICE_UPDATED'
  | 'DEVICE_DEREGISTERED'

  // ── OTP ────────────────────────────────────────────────────────────────────
  | 'OTP_SENT'
  | 'OTP_VERIFIED'
  | 'OTP_VERIFICATION_FAILED'

  // ── Admin ──────────────────────────────────────────────────────────────────
  | 'ADMIN_ACCOUNT_DELETED';

/**
 * Constant object providing IDE autocompletion and preventing typos at call-sites.
 *
 * @example
 * ```ts
 * this.logger.event(LOG_EVENT.LIKE_CREATED, { likeId, userId });
 * ```
 */
export const LOG_EVENT = {
  // Request Lifecycle
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
  REQUEST_FAILED: 'REQUEST_FAILED',

  // Authentication
  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_AUTHENTICATION_FAILED: 'USER_AUTHENTICATION_FAILED',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_PROVISIONED: 'USER_PROVISIONED',
  SECONDARY_AUTH_ADDED: 'SECONDARY_AUTH_ADDED',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',

  // Likes
  LIKE_CREATED: 'LIKE_CREATED',
  LIKE_DELETED: 'LIKE_DELETED',
  LIKE_LABEL_UPDATED: 'LIKE_LABEL_UPDATED',
  LIKE_CREATION_DENIED: 'LIKE_CREATION_DENIED',

  // Blocks
  BLOCK_CREATED: 'BLOCK_CREATED',
  BLOCK_REMOVED: 'BLOCK_REMOVED',

  // Chats
  CHAT_HISTORY_CLEARED: 'CHAT_HISTORY_CLEARED',

  // Credits
  CREDITS_BALANCE_CHECKED: 'CREDITS_BALANCE_CHECKED',
  CREDITS_GRANTED: 'CREDITS_GRANTED',
  CREDITS_DEDUCTED: 'CREDITS_DEDUCTED',
  CREDITS_EXPIRY_BATCH_STARTED: 'CREDITS_EXPIRY_BATCH_STARTED',
  CREDITS_EXPIRY_BATCH_COMPLETED: 'CREDITS_EXPIRY_BATCH_COMPLETED',
  CREDITS_EXPIRY_WARNING_SENT: 'CREDITS_EXPIRY_WARNING_SENT',

  // Matches
  MATCH_CREATED: 'MATCH_CREATED',
  MATCH_DISSOLVED: 'MATCH_DISSOLVED',
  MATCH_RESOLUTION_TRIGGERED: 'MATCH_RESOLUTION_TRIGGERED',
  MATCH_RESOLUTION_FAILED: 'MATCH_RESOLUTION_FAILED',

  // Subscriptions & Payments
  TRANSACTION_RECORDED: 'TRANSACTION_RECORDED',
  META_WEBHOOK_VERIFIED: 'META_WEBHOOK_VERIFIED',
  SUBSCRIPTION_PURCHASE_INITIATED: 'SUBSCRIPTION_PURCHASE_INITIATED',
  SUBSCRIPTION_PURCHASE_COMPLETED: 'SUBSCRIPTION_PURCHASE_COMPLETED',
  SUBSCRIPTION_PURCHASE_FAILED: 'SUBSCRIPTION_PURCHASE_FAILED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_REFUNDED: 'SUBSCRIPTION_REFUNDED',
  SUBSCRIPTION_WEBHOOK_RECEIVED: 'SUBSCRIPTION_WEBHOOK_RECEIVED',
  SUBSCRIPTION_WEBHOOK_PROCESSED: 'SUBSCRIPTION_WEBHOOK_PROCESSED',
  SUBSCRIPTION_WEBHOOK_FAILED: 'SUBSCRIPTION_WEBHOOK_FAILED',

  // Notifications
  NOTIFICATION_REQUESTED: 'NOTIFICATION_REQUESTED',
  NOTIFICATION_QUEUED: 'NOTIFICATION_QUEUED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  PUSH_NOTIFICATION_SENT: 'PUSH_NOTIFICATION_SENT',
  PUSH_NOTIFICATION_FAILED: 'PUSH_NOTIFICATION_FAILED',
  EMAIL_QUEUED: 'EMAIL_QUEUED',
  EMAIL_SENT: 'EMAIL_SENT',
  EMAIL_FAILED: 'EMAIL_FAILED',

  // Profiles & Identities
  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILE_DELETED: 'PROFILE_DELETED',
  PREFERENCES_UPDATED: 'PREFERENCES_UPDATED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  IDENTITY_CLAIMED: 'IDENTITY_CLAIMED',
  IDENTITY_CREATED: 'IDENTITY_CREATED',
  IDENTITY_RESOLVED: 'IDENTITY_RESOLVED',
  IDENTITY_UPDATED: 'IDENTITY_UPDATED',
  IDENTITY_DELETED: 'IDENTITY_DELETED',
  IDENTITY_VERIFIED: 'IDENTITY_VERIFIED',

  // Workflows
  INSTAGRAM_IDENTITY_LINKED: 'INSTAGRAM_IDENTITY_LINKED',
  SOCIAL_IDENTITY_VERIFIED: 'SOCIAL_IDENTITY_VERIFIED',

  // Subscriptions
  SUBSCRIPTION_EXPIRED_BATCH: 'SUBSCRIPTION_EXPIRED_BATCH',
  MATCH_RESOLUTION_COMPLETED: 'MATCH_RESOLUTION_COMPLETED',

  // Pub/Sub
  PUBSUB_MESSAGE_RECEIVED: 'PUBSUB_MESSAGE_RECEIVED',
  PUBSUB_MESSAGE_ROUTED: 'PUBSUB_MESSAGE_ROUTED',
  PUBSUB_MESSAGE_PROCESSED: 'PUBSUB_MESSAGE_PROCESSED',
  PUBSUB_MESSAGE_FAILED: 'PUBSUB_MESSAGE_FAILED',
  PUBSUB_EVENT_PUBLISHED: 'PUBSUB_EVENT_PUBLISHED',
  PUBSUB_PUBLISH_FAILED: 'PUBSUB_PUBLISH_FAILED',

  // Audit
  AUDIT_EVENT_EMITTED: 'AUDIT_EVENT_EMITTED',
  AUDIT_EVENT_FAILED: 'AUDIT_EVENT_FAILED',

  // External Services
  EXTERNAL_REQUEST_STARTED: 'EXTERNAL_REQUEST_STARTED',
  EXTERNAL_REQUEST_COMPLETED: 'EXTERNAL_REQUEST_COMPLETED',
  EXTERNAL_REQUEST_FAILED: 'EXTERNAL_REQUEST_FAILED',

  // Devices
  DEVICE_REGISTERED: 'DEVICE_REGISTERED',
  DEVICE_UPDATED: 'DEVICE_UPDATED',
  DEVICE_DEREGISTERED: 'DEVICE_DEREGISTERED',

  // OTP
  OTP_SENT: 'OTP_SENT',
  OTP_VERIFIED: 'OTP_VERIFIED',
  OTP_VERIFICATION_FAILED: 'OTP_VERIFICATION_FAILED',

  // Admin
  ADMIN_ACCOUNT_DELETED: 'ADMIN_ACCOUNT_DELETED',
} as const satisfies Record<LogEvent, LogEvent>;
